### ISSUE TITLE
Build issues with numpy 1.24.1

### ISSUE THREAD

**Issue by tilmantroester** [tilmantroester/pyhmcode#3]
The c code generated by f2py fails to compile with the numpy 1.24.1 version of f2py, with error message `error: use of undeclared identifier 'capi_this_tmp';`.

**Comment by tilmantroester** [comment]
This seems to be fixed with recent releases of f90wrap.
